version: '3.9'
services:
  app:
    image: python-alembic-example
    build:
      context: .
    tty: true
    volumes:
      - ./src:/home/python/src
  db:
    image: postgres:11-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-python_database}
